// dart format off
// coverage:ignore-file
// ignore_for_file: type=hint,type=lint,type=warning
//
// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// **************************************************************************
import 'package:example_route_extension/src/interceptors/login_interceptor.dart';
import 'package:example_route_extension/src/interceptors/permission_interceptor.dart';
import 'package:ff_annotation_route_library/ff_annotation_route_library.dart';
import 'package:flutter/widgets.dart';

import 'src/pages/home_page.dart';
import 'src/pages/login_page.dart';
import 'src/pages/page_a.dart';
import 'src/pages/page_b.dart';

/// The routeInterceptors auto generated by https://github.com/fluttercandies/ff_annotation_route
const Map<String, List<RouteInterceptor>> routeInterceptors =
    <String, List<RouteInterceptor>>{
      'fluttercandies://PageA': <RouteInterceptor>[LoginInterceptor()],
      'fluttercandies://PageB': <RouteInterceptor>[
        LoginInterceptor(),
        PermissionInterceptor(),
      ],
    };

/// Get route settings base on route name, auto generated by https://github.com/fluttercandies/ff_annotation_route
FFRouteSettings getRouteSettings({
  required String name,
  Map<String, dynamic>? arguments,
  PageBuilder? notFoundPageBuilder,
}) {
  Map<String, dynamic> safeArguments = arguments ?? const <String, dynamic>{};
  if (arguments != null && arguments.isNotEmpty) {
    final Map<String, dynamic> ignoreCaseMap = <String, dynamic>{};
    safeArguments.forEach((String key, dynamic value) {
      ignoreCaseMap[key.toLowerCase()] = value;
    });
    safeArguments = ignoreCaseMap;
  }
  switch (name) {
    case 'fluttercandies://HomePage':
      return FFRouteSettings(
        name: 'fluttercandies://HomePage',
        routeName: 'HomePage',
        description: 'HomePage',
        arguments: arguments,
        builder: () => HomePage(key: asT<Key?>(safeArguments['key'])),
      );
    case 'fluttercandies://LoginPage':
      return FFRouteSettings(
        name: 'fluttercandies://LoginPage',
        routeName: 'LoginPage',
        description: 'LoginPage',
        arguments: arguments,
        builder: () => LoginPage(key: asT<Key?>(safeArguments['key'])),
      );
    case 'fluttercandies://PageA':
      return FFRouteSettings(
        name: 'fluttercandies://PageA',
        routeName: 'PageA',
        description: 'PageA',
        arguments: arguments,
        builder: () => PageA(key: asT<Key?>(safeArguments['key'])),
      );
    case 'fluttercandies://PageB':
      return FFRouteSettings(
        name: 'fluttercandies://PageB',
        routeName: 'PageB',
        description: 'PageB',
        arguments: arguments,
        builder: () => PageB(key: asT<Key?>(safeArguments['key'])),
      );
    default:
      return FFRouteSettings(
        name: FFRoute.notFoundName,
        routeName: FFRoute.notFoundRouteName,
        builder: notFoundPageBuilder ?? () => Container(),
      );
  }
}
