// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// version: 10.1.0
// **************************************************************************
// ignore_for_file: duplicate_import,implementation_imports,library_private_types_in_public_api,multiple_combinators,prefer_const_literals_to_create_immutables,unintended_html_in_doc_comment,unnecessary_import,unused_import,unused_local_variable,unused_shown_name, unnecessary_library_name
import 'package:example_getx/src/bindings/bindings1.dart';
import 'package:flutter/foundation.dart';

import 'src/pages/main_page.dart';

/// The routeNames auto generated by https://github.com/fluttercandies/ff_annotation_route
const List<String> routeNames = <String>[
  '/BindingsPage',
  '/ControllerPage',
  '/CounterPage',
  '/ItemPage',
  'fluttercandies://demogrouppage',
  'fluttercandies://mainpage',
];

/// The routes auto generated by https://github.com/fluttercandies/ff_annotation_route
class Routes {
  const Routes._();

  /// 'how to use Bindings with Annotation.'
  ///
  /// [name] : '/BindingsPage'
  ///
  /// [routeName] : 'BindingsPage'
  ///
  /// [description] : 'how to use Bindings with Annotation.'
  ///
  /// [constructors] :
  ///
  /// BindingsPage : [String? argument]
  ///
  /// [exts] : {'group': 'demo', 'order': 1}
  static const _BindingsPage bindingsPage = _BindingsPage();

  /// 'This is getX demo.'
  ///
  /// [name] : '/ControllerPage'
  ///
  /// [routeName] : 'ControllerPage'
  ///
  /// [description] : 'This is getX demo.'
  ///
  /// [exts] : {'group': 'demo', 'order': 0}
  static const _ControllerPage controllerPage = _ControllerPage();

  /// 'This is getX counter demo.'
  ///
  /// [name] : '/CounterPage'
  ///
  /// [description] : 'This is getX counter demo.'
  static const _CounterPage counterPage = _CounterPage();

  /// '/ItemPage'
  ///
  /// [name] : '/ItemPage'
  ///
  /// [constructors] :
  ///
  /// ItemPage : [int(required) index]
  static const _ItemPage itemPage = _ItemPage();

  /// 'DemoGroupPage'
  ///
  /// [name] : 'fluttercandies://demogrouppage'
  ///
  /// [routeName] : 'DemoGroupPage'
  ///
  /// [constructors] :
  ///
  /// DemoGroupPage : [MapEntry<String, List<DemoRouteResult>>(required) keyValue]
  static const _FluttercandiesDemogrouppage fluttercandiesDemogrouppage =
      _FluttercandiesDemogrouppage();

  /// 'MainPage'
  ///
  /// [name] : 'fluttercandies://mainpage'
  ///
  /// [routeName] : 'MainPage'
  static const _FluttercandiesMainpage fluttercandiesMainpage =
      _FluttercandiesMainpage();
}

class _BindingsPage {
  const _BindingsPage();

  String get name => '/BindingsPage';

  Map<String, dynamic> d({
    Key? key,
    String? argument,
  }) =>
      <String, dynamic>{
        'key': key,
        'argument': argument,
      };

  @override
  String toString() => name;
}

class _ControllerPage {
  const _ControllerPage();

  String get name => '/ControllerPage';

  Map<String, dynamic> d({
    Key? key,
  }) =>
      <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _CounterPage {
  const _CounterPage();

  String get name => '/CounterPage';

  Map<String, dynamic> d({
    Key? key,
  }) =>
      <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _ItemPage {
  const _ItemPage();

  String get name => '/ItemPage';

  Map<String, dynamic> d({
    required int index,
    Key? key,
  }) =>
      <String, dynamic>{
        'index': index,
        'key': key,
      };

  @override
  String toString() => name;
}

class _FluttercandiesDemogrouppage {
  const _FluttercandiesDemogrouppage();

  String get name => 'fluttercandies://demogrouppage';

  Map<String, dynamic> d({
    Key? key,
    required MapEntry<String, List<DemoRouteResult>> keyValue,
  }) =>
      <String, dynamic>{
        'key': key,
        'keyValue': keyValue,
      };

  @override
  String toString() => name;
}

class _FluttercandiesMainpage {
  const _FluttercandiesMainpage();

  String get name => 'fluttercandies://mainpage';

  Map<String, dynamic> d({
    Key? key,
  }) =>
      <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}
