// dart format off
// coverage:ignore-file
// ignore_for_file: duplicate_import,implementation_imports,library_private_types_in_public_api,multiple_combinators,prefer_const_literals_to_create_immutables,unintended_html_in_doc_comment,unnecessary_import,unnecessary_library_directive,unnecessary_library_name,unused_import,unused_local_variable,unused_shown_name
//
// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// **************************************************************************
import 'package:example_getx/src/bindings/bindings1.dart';
import 'package:ff_annotation_route_library/ff_annotation_route_library.dart';
import 'package:flutter/widgets.dart';

import 'src/pages/bindings_page.dart';
import 'src/pages/controller_page.dart';
import 'src/pages/counter_page.dart';
import 'src/pages/item_page.dart';
import 'src/pages/main_page.dart';

/// Get route settings base on route name, auto generated by https://github.com/fluttercandies/ff_annotation_route
FFRouteSettings getRouteSettings({
  required String name,
  Map<String, dynamic>? arguments,
  PageBuilder? notFoundPageBuilder,
}) {
  final Map<String, dynamic> safeArguments =
      arguments ?? const <String, dynamic>{};
  switch (name) {
    case '/BindingsPage':
      return FFRouteSettings(
        name: '/BindingsPage',
        routeName: 'BindingsPage',
        description: 'how to use Bindings with Annotation.',
        arguments: arguments,
        codes: <String, dynamic>{'binding': Bindings1()},
        exts: <String, dynamic>{'group': 'demo', 'order': 1},
        builder: () => BindingsPage(
          key: asT<Key?>(safeArguments['key']),
          argument: asT<String?>(safeArguments['argument']),
        ),
      );
    case '/ControllerPage':
      return FFRouteSettings(
        name: '/ControllerPage',
        routeName: 'ControllerPage',
        description: 'This is getX demo.',
        arguments: arguments,
        exts: <String, dynamic>{'group': 'demo', 'order': 0},
        builder: () => ControllerPage(key: asT<Key?>(safeArguments['key'])),
      );
    case '/CounterPage':
      return FFRouteSettings(
        name: '/CounterPage',
        description: 'This is getX counter demo.',
        arguments: arguments,
        builder: () => CounterPage(key: asT<Key?>(safeArguments['key'])),
      );
    case '/ItemPage':
      return FFRouteSettings(
        name: '/ItemPage',
        arguments: arguments,
        builder: () => ItemPage(
          index: asT<int>(safeArguments['index'])!,
          key: asT<Key?>(safeArguments['key']),
        ),
      );
    case 'fluttercandies://demogrouppage':
      return FFRouteSettings(
        name: 'fluttercandies://demogrouppage',
        routeName: 'DemoGroupPage',
        arguments: arguments,
        builder: () => DemoGroupPage(
          key: asT<Key?>(safeArguments['key']),
          keyValue: asT<MapEntry<String, List<DemoRouteResult>>>(
            safeArguments['keyValue'],
          )!,
        ),
      );
    case 'fluttercandies://mainpage':
      return FFRouteSettings(
        name: 'fluttercandies://mainpage',
        routeName: 'MainPage',
        arguments: arguments,
        builder: () => MainPage(key: asT<Key?>(safeArguments['key'])),
      );
    default:
      return FFRouteSettings(
        name: FFRoute.notFoundName,
        routeName: FFRoute.notFoundRouteName,
        builder: notFoundPageBuilder ?? () => Container(),
      );
  }
}
