// dart format off
// coverage:ignore-file
// ignore_for_file: duplicate_import,implementation_imports,library_private_types_in_public_api,multiple_combinators,prefer_const_literals_to_create_immutables,unintended_html_in_doc_comment,unnecessary_import,unnecessary_library_directive,unnecessary_library_name,unused_import,unused_local_variable,unused_shown_name
//
// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// **************************************************************************
library module_a_fast_route;

export 'src/test_page_b.dart';
export 'src/test_page_c.dart';
export 'src/test_page_d.dart';
export 'src/test_page_f.dart';
