name: example_fast_mode
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  module_a:
    path: module_a

  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  ff_annotation_route_core: ^2.1.0
  ff_annotation_route_library: ^3.0.0
  functional_widget_annotation: ^0.10.0
  url_launcher: ^6.0.2

  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1

dev_dependencies:
  flutter_lints: any
  build_runner: ^2.2.0
  functional_widget: ^0.10.0

flutter:
  uses-material-design: true
