import 'package:collection/collection.dart' show IterableComparableExtension;

import '/src/arg/args.dart';

Type typeOf<T>() => T;

List<String> get ignores {
  return [
    'duplicate_import',
    'implementation_imports',
    'library_private_types_in_public_api',
    'multiple_combinators',
    'prefer_const_literals_to_create_immutables',
    'unintended_html_in_doc_comment',
    'unnecessary_import',
    'unnecessary_library_directive',
    'unnecessary_library_name',
    'unused_import',
    'unused_local_variable',
    'unused_shown_name',
  ].sorted();
}

String get headerLicense {
  return '''// coverage:ignore-file
// ignore_for_file: ${ignores.join(',')}
//
// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route 
// **************************************************************************
// fast mode: ${Args().isFastMode}
// **************************************************************************
''';
}

const String headerFormatOff = '// dart format off';

const String rootFile = '''
{4}
{5}
/// Get route settings base on route name, auto generated by https://github.com/fluttercandies/ff_annotation_route 
FFRouteSettings getRouteSettings({
  {1} String name,
  Map<String, dynamic>{2} arguments,
  PageBuilder{2} notFoundPageBuilder,
}) {
  {3}    
  switch (name) {
{0}   default:
    return FFRouteSettings(
      name: FFRoute.notFoundName,
      routeName: FFRoute.notFoundRouteName,
      builder: notFoundPageBuilder ?? () => Container(),
    );
  }
}
''';

const String goRouterRootFile = '''
{1}
{2}
/// Get route settings base on route name, auto generated by https://github.com/fluttercandies/ff_annotation_route 
final List<FFGoRouterRouteSettings> goRouterRouteSettings = <FFGoRouterRouteSettings>[{0}];
''';
