Type typeOf<T>() => T;

const String fileHeader = '''// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import
''';

/// ignore_for_file: argument_type_not_assignable

const String rootFile = '''
FFRouteSettings getRouteSettings({
  {1} String name,
  Map<String, dynamic>{2} arguments,
  Widget{2} notFoundWidget,
}) {
  final Map<String, dynamic> safeArguments =
      arguments ?? const <String, dynamic>{};
  switch (name) {
{0}   default:
    return FFRouteSettings(
      name: FFRoute.notFoundName,
      routeName: FFRoute.notFoundRouteName,
      widget: notFoundWidget,
    );
  }
}
''';
