Type typeOf<T>() => T;

const String fileHeader = '''// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
''';

/// ignore_for_file: argument_type_not_assignable

const String rootFile = """

// ignore_for_file: prefer_const_literals_to_create_immutables
FFRouteSettings getRouteSettings({{1} String name, Map<String, dynamic>{2} arguments,}) {
  final Map<String, dynamic> safeArguments =arguments ?? const <String, dynamic>{};
  switch (name) {
{0}   default:
      return const FFRouteSettings(name:'404',routeName: '404_page');
  }
}
""";
