// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************

library module_text_route;

export 'src/background_text_demo.dart';
export 'src/custom_image_demo.dart';
export 'src/custom_text_overflow_demo.dart';
export 'src/text_demo.dart';
export 'src/text_selection_demo.dart';
