// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************

import 'package:example/src/model/test_model.dart' hide TestMode2;
import 'package:example/src/model/test_model1.dart' hide TestMode3;
import 'package:ff_annotation_route_library/ff_annotation_route_library.dart';
import 'package:flutter/widgets.dart';
import 'package:module_a/module_a_route.dart';

import 'src/pages/complex/test_page_d.dart';
import 'src/pages/complex/test_page_e.dart';
import 'src/pages/main_page.dart';
import 'src/pages/simple/test_page_a.dart';
import 'src/pages/simple/test_page_b.dart';

// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import
FFRouteSettings getRouteSettings({
  required String name,
  Map<String, dynamic>? arguments,
}) {
  final Map<String, dynamic> safeArguments =
      arguments ?? const <String, dynamic>{};
  switch (name) {
    case '''flutterCandies://testPage' "B''':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        widget: TestPageB(
          argument: asT<String?>(safeArguments['argument']),
        ),
        routeName: 'testPageB ',
        pageRouteType: PageRouteType.material,
        description: "This is test ' page B.",
        exts: <String, dynamic>{'group': 'Simple', 'order': 1},
      );
    case '''flutterCandies://testPage' "D''':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        widget: <String, Widget>{
          '': TestPageD(
            asT<String?>(safeArguments['argument']),
            optional: asT<bool?>(safeArguments['optional'], false),
            id: asT<String?>(safeArguments['id'], 'flutterCandies'),
          ),
          'another0': TestPageD.another0(
            argument: asT<String?>(safeArguments['argument']),
          ),
          'another1': TestPageD.another1(
            asT<String?>(safeArguments['argument']),
            asT<bool?>(safeArguments['optional'], false),
          ),
          'another2': TestPageD.another2(
            asT<String?>(safeArguments['argument']),
          ),
          'another3': TestPageD.another3(
            asT<String?>(safeArguments['argument']),
            optional: asT<bool?>(safeArguments['optional']),
          ),
        }[safeArguments[constructorName] != null
            ? safeArguments[constructorName] as String
            : ''],
        routeName: 'testPageD ',
        pageRouteType: PageRouteType.material,
        description: "This is test ' page D.",
        exts: <String, dynamic>{'group': 'Complex', 'order': 0},
      );
    case 'flutterCandies://testPageA':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        widget: TestPageA(),
        routeName: 'testPageA',
        description: 'This is test page A.',
        exts: <String, dynamic>{'group': 'Simple', 'order': 0},
      );
    case 'flutterCandies://testPageC':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        widget: TestPageC(),
        routeName: 'testPageC',
        description: 'This is test page c in other module.',
        exts: <String, dynamic>{'group': 'Simple', 'order': 2},
      );
    case 'flutterCandies://testPageE':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        widget: <String, Widget>{
          '': TestPageE(
            testMode: asT<TestMode?>(safeArguments['testMode'],
                const TestMode(id: 2, isTest: false)),
            testMode1: asT<TestMode1?>(safeArguments['testMode1']),
          ),
          'test': TestPageE.test(),
          'requiredC': TestPageE.requiredC(
            testMode: asT<TestMode?>(safeArguments['testMode']),
          ),
        }[safeArguments[constructorName] != null
            ? safeArguments[constructorName] as String
            : ''],
        routeName: 'testPageE',
        description: 'Show how to push new page with arguments(class)',
        exts: <String, dynamic>{'group': 'Complex', 'order': 1},
      );
    case 'fluttercandies://demogrouppage':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        widget: DemoGroupPage(
          keyValue: asT<MapEntry<String, List<DemoRouteResult>>>(
              safeArguments['keyValue'])!,
        ),
        routeName: 'DemoGroupPage',
      );
    case 'fluttercandies://mainpage':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        widget: MainPage(),
        routeName: 'MainPage',
      );
    default:
      return const FFRouteSettings(name: '404', routeName: '404_page');
  }
}
