// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: false
// **************************************************************************
// ignore_for_file: duplicate_import,implementation_imports,library_private_types_in_public_api,multiple_combinators,prefer_const_literals_to_create_immutables,unintended_html_in_doc_comment,unnecessary_import,unused_import,unused_local_variable,unused_shown_name,unnecessary_library_name,unnecessary_library_directive
import 'dart:io' as autoimportd66e09f4babbdbbe015b32cc3816761d;
import 'dart:ui' as autoimportde7367a4dccc7f836046967508c09a6c;

import 'package:example/src/model/test_model.dart'
    as autoimport7b0d8961824b1df42839aaf6ee621592;
import 'package:example/src/model/test_model1.dart'
    as autoimportfd790b2c4cbc8e7d99977cab283b94ab;
import 'package:example/src/model/test_model2.dart'
    as autoimport14790b17a5a1427ada8188fbf75b352c;
import 'package:example/src/pages/main_page.dart'
    as autoimport19a8136766d530a60dc5d464509fd9eb;
import 'package:example/src/typedef.dart'
    as autoimport012d709d6940bda4da65ad673a93e8a3;
import 'package:extended_image/src/utils.dart'
    as autoimporte9848a6dfb6bcdd3203dea5d89c0972f;
import 'package:flutter/foundation.dart';
import 'package:flutter/src/foundation/key.dart'
    as autoimport61a64860a48a0a727515bc4ec00b2fff;
import 'package:flutter/src/gestures/drag_details.dart'
    as autoimport1e2f7b96e6c9c283a2a35bf82237bf16;
import 'package:flutter/src/widgets/framework.dart'
    as autoimport2ac85d6b777135304f548b8ca2707514;
import 'package:module_a/src/mode/mode.dart'
    as autoimportac41f6e44f4086b72b4f7dbc1ab40cc1;
import 'package:module_a/src/mode/mode.dart' as module_a;

/// The routeNames auto generated by https://github.com/fluttercandies/ff_annotation_route
const List<String> routeNames = <String>[
  'flutterCandies://TestPageF',
  'flutterCandies://TestPageSuperParameters',
  'flutterCandies://func',
  'flutterCandies://func1',
  'flutterCandies://func2',
  'flutterCandies://func3',
  'flutterCandies://func4',
  'flutterCandies://func5',
  'flutterCandies://func7',
  '''flutterCandies://testPage' "B''',
  '''flutterCandies://testPage' "B_Copy''',
  '''flutterCandies://testPage' "B_Copy_Copy''',
  '''flutterCandies://testPage' "B_module_a''',
  '''flutterCandies://testPage' "D''',
  'flutterCandies://testPageA',
  'flutterCandies://testPageC',
  'flutterCandies://testPageCC',
  'flutterCandies://testPageC_Copy',
  'flutterCandies://testPageC_Copy_Copy',
  'flutterCandies://testPageD_moduleA',
  'flutterCandies://testPageE',
  'flutterCandies://testPageF_moduleA',
  'fluttercandies://demogrouppage',
  'fluttercandies://mainpage',
];

/// The routes auto generated by https://github.com/fluttercandies/ff_annotation_route
class Routes {
  const Routes._();

  /// 'Show how to push new page with arguments(class)'
  ///
  /// [name] : 'flutterCandies://TestPageF'
  ///
  /// [routeName] : 'TestPageF'
  ///
  /// [description] : 'Show how to push new page with arguments(class)'
  ///
  /// [constructors] :
  ///
  /// TestPageF({Key? key, BoxWidthStyle boxWidthStyle = ui.BoxWidthStyle.max, ExtendedImageMode extendedImageMode = ExtendedImageMode.gesture, required DragDownDetails details, required BlendMode blendMode, required File file, required List<TestMode3> modes, required Widget Function(String) function, required TestMode3 Function(DragDownDetails) function1, required TestMode3 Function(Map<TestMode1, TestMode2>) function2, required bool Function(String) Function(int, TestMode2 Function(DragDownDetails)) function3, required int Function(String) aFunction, required int myInt, required int Function(String) Function(int Function(String)) Function(int, int Function(int)) function4, TypedefClass1 typedefClass1 = const type.TypedefClass1(1)})
  ///
  /// [exts] : {'group': 'Complex', 'order': 2}
  static const _FlutterCandiesTestPageF flutterCandiesTestPageF =
      _FlutterCandiesTestPageF();

  /// 'This is super parameter test page.'
  ///
  /// [name] : 'flutterCandies://TestPageSuperParameters'
  ///
  /// [routeName] : 'TestPageSuperParameters '
  ///
  /// [description] : 'This is super parameter test page.'
  ///
  /// [constructors] :
  ///
  /// TestPageSuperParameters({Key? key, TestMode? argument, String title = 'abc'})
  ///
  /// [pageRouteType] : PageRouteType.material
  ///
  /// [exts] : {'group': 'Complex', 'order': 2}
  static const _FlutterCandiesTestPageSuperParameters
      flutterCandiesTestPageSuperParameters =
      _FlutterCandiesTestPageSuperParameters();

  /// 'test-func'
  ///
  /// [name] : 'flutterCandies://func'
  ///
  /// [routeName] : 'test-func'
  ///
  /// [constructors] :
  ///
  /// Func(int a, String? b, {Key? key, bool? c, required double d})
  static const _FlutterCandiesFunc flutterCandiesFunc = _FlutterCandiesFunc();

  /// 'test-func-1'
  ///
  /// [name] : 'flutterCandies://func1'
  ///
  /// [routeName] : 'test-func-1'
  ///
  /// [constructors] :
  ///
  /// Func1(int a, String? b, {Key? key, bool? c, required double d})
  static const _FlutterCandiesFunc1 flutterCandiesFunc1 =
      _FlutterCandiesFunc1();

  /// 'test-func-2'
  ///
  /// [name] : 'flutterCandies://func2'
  ///
  /// [routeName] : 'test-func-2'
  ///
  /// [constructors] :
  ///
  /// Func2(int a, String? b, {Key? key, bool? c, required double d})
  static const _FlutterCandiesFunc2 flutterCandiesFunc2 =
      _FlutterCandiesFunc2();

  /// 'test-func-3'
  ///
  /// [name] : 'flutterCandies://func3'
  ///
  /// [routeName] : 'test-func-3'
  ///
  /// [constructors] :
  ///
  /// Func3(int a, String? b, {Key? key, bool? c, required double d})
  static const _FlutterCandiesFunc3 flutterCandiesFunc3 =
      _FlutterCandiesFunc3();

  /// 'test-func-4'
  ///
  /// [name] : 'flutterCandies://func4'
  ///
  /// [routeName] : 'test-func-4'
  ///
  /// [constructors] :
  ///
  /// Func4(int a, String? b, {Key? key, bool? c, required double d})
  static const _FlutterCandiesFunc4 flutterCandiesFunc4 =
      _FlutterCandiesFunc4();

  /// 'test-func-5'
  ///
  /// [name] : 'flutterCandies://func5'
  ///
  /// [routeName] : 'test-func-5'
  ///
  /// [constructors] :
  ///
  /// Func5(int a, String? b, {Key? key, bool? c, required double d})
  static const _FlutterCandiesFunc5 flutterCandiesFunc5 =
      _FlutterCandiesFunc5();

  /// 'test-func-7'
  ///
  /// [name] : 'flutterCandies://func7'
  ///
  /// [routeName] : 'test-func-7'
  ///
  /// [constructors] :
  ///
  /// $7Func(int a, String? b, {Key? key, bool? c, required double d})
  static const _FlutterCandiesFunc7 flutterCandiesFunc7 =
      _FlutterCandiesFunc7();

  /// "This is test ' page B."
  ///
  /// [name] : '''flutterCandies://testPage' "B'''
  ///
  /// [routeName] : 'testPageB '
  ///
  /// [description] : "This is test ' page B."
  ///
  /// [constructors] :
  ///
  /// TestPageB({Key? key, String? argument})
  ///
  /// [pageRouteType] : PageRouteType.material
  ///
  /// [exts] : {'group': 'Simple', 'order': 1}
  static const _FlutterCandiesTestPageB flutterCandiesTestPageB =
      _FlutterCandiesTestPageB();

  /// "This is test ' page B. has the same name"
  ///
  /// [name] : '''flutterCandies://testPage' "B_Copy'''
  ///
  /// [routeName] : 'testPageB '
  ///
  /// [description] : "This is test ' page B. has the same name"
  ///
  /// [constructors] :
  ///
  /// TestPageB({Key? key, String? argument})
  ///
  /// [pageRouteType] : PageRouteType.material
  ///
  /// [exts] : {'group': 'Simple', 'order': 1}
  static const _FlutterCandiesTestPageBCopy flutterCandiesTestPageBCopy =
      _FlutterCandiesTestPageBCopy();

  /// "This is test ' page B. has the same name"
  ///
  /// [name] : '''flutterCandies://testPage' "B_Copy_Copy'''
  ///
  /// [routeName] : 'testPageB '
  ///
  /// [description] : "This is test ' page B. has the same name"
  ///
  /// [constructors] :
  ///
  /// TestPageB({Key? key, String? argument})
  ///
  /// [pageRouteType] : PageRouteType.material
  ///
  /// [exts] : {'group': 'Simple', 'order': 1}
  static const _FlutterCandiesTestPageBCopyCopy
      flutterCandiesTestPageBCopyCopy = _FlutterCandiesTestPageBCopyCopy();

  /// "This is test ' page B. in module a"
  ///
  /// [name] : '''flutterCandies://testPage' "B_module_a'''
  ///
  /// [routeName] : 'testPageB '
  ///
  /// [description] : "This is test ' page B. in module a"
  ///
  /// [constructors] :
  ///
  /// TestPageB({Key? key, TestMode? argument, String title = 'dddd'})
  ///
  /// [pageRouteType] : PageRouteType.material
  ///
  /// [exts] : {'group': 'Simple', 'order': 1}
  static const _FlutterCandiesTestPageBModuleA flutterCandiesTestPageBModuleA =
      _FlutterCandiesTestPageBModuleA();

  /// "This is test ' page D."
  ///
  /// [name] : '''flutterCandies://testPage' "D'''
  ///
  /// [routeName] : 'testPageD '
  ///
  /// [description] : "This is test ' page D."
  ///
  /// [constructors] :
  ///
  /// TestPageD(String? argument, {Key? key, bool? optional = false, String? id = 'flutterCandies', dynamic anything})
  ///
  /// TestPageD.another0({required String? argument})
  ///
  /// TestPageD.another1(String? argument, [bool? optional = false])
  ///
  /// TestPageD.another2(String? argument)
  ///
  /// TestPageD.another3(String? argument, {bool? optional, dynamic anything})
  ///
  /// [pageRouteType] : PageRouteType.material
  ///
  /// [exts] : {'group': 'Complex', 'order': 0}
  static const _FlutterCandiesTestPageD flutterCandiesTestPageD =
      _FlutterCandiesTestPageD();

  /// 'This is test page A.'
  ///
  /// [name] : 'flutterCandies://testPageA'
  ///
  /// [routeName] : 'testPageA'
  ///
  /// [description] : 'This is test page A.'
  ///
  /// [constructors] :
  ///
  /// TestPageA({Key? key})
  ///
  /// [exts] : {'group': 'Simple', 'order': 0, 'test6': TestPageA.dd}
  static const _FlutterCandiesTestPageA flutterCandiesTestPageA =
      _FlutterCandiesTestPageA();

  /// 'This is test page c in other module.'
  ///
  /// [name] : 'flutterCandies://testPageC'
  ///
  /// [routeName] : 'testPageC'
  ///
  /// [description] : 'This is test page c in other module.'
  ///
  /// [constructors] :
  ///
  /// TestPageC({Key? key})
  ///
  /// [exts] : {'group': 'Simple', 'order': 2}
  static const _FlutterCandiesTestPageC flutterCandiesTestPageC =
      _FlutterCandiesTestPageC();

  /// 'This is test page CC.'
  ///
  /// [name] : 'flutterCandies://testPageCC'
  ///
  /// [routeName] : 'testPageCC'
  ///
  /// [description] : 'This is test page CC.'
  ///
  /// [constructors] :
  ///
  /// TestPageCC(int testArg, {Key? key, required String testRequiredArg, bool? testBoolean})
  ///
  /// TestPageCC.positioned(int testArg, [bool? testBoolean, String testRequiredArg = '', Key? key])
  static const _FlutterCandiesTestPageCC flutterCandiesTestPageCC =
      _FlutterCandiesTestPageCC();

  /// 'This is test page c has the same name with moudle_a TestPageC.'
  ///
  /// [name] : 'flutterCandies://testPageC_Copy'
  ///
  /// [routeName] : 'testPageC'
  ///
  /// [description] : 'This is test page c has the same name with moudle_a TestPageC.'
  ///
  /// [constructors] :
  ///
  /// TestPageC({Key? key})
  ///
  /// [exts] : {'group': 'Simple', 'order': 2}
  static const _FlutterCandiesTestPageCCopy flutterCandiesTestPageCCopy =
      _FlutterCandiesTestPageCCopy();

  /// 'This is test page c has the same name with moudle_a TestPageC.'
  ///
  /// [name] : 'flutterCandies://testPageC_Copy_Copy'
  ///
  /// [routeName] : 'testPageC'
  ///
  /// [description] : 'This is test page c has the same name with moudle_a TestPageC.'
  ///
  /// [constructors] :
  ///
  /// TestPageC({Key? key})
  ///
  /// [exts] : {'group': 'Simple', 'order': 2}
  static const _FlutterCandiesTestPageCCopyCopy
      flutterCandiesTestPageCCopyCopy = _FlutterCandiesTestPageCCopyCopy();

  /// 'This is test page D. in module a'
  ///
  /// [name] : 'flutterCandies://testPageD_moduleA'
  ///
  /// [routeName] : 'testPageA'
  ///
  /// [description] : 'This is test page D. in module a'
  ///
  /// [constructors] :
  ///
  /// TestPageD({Key? key})
  ///
  /// [exts] : {'group': 'Simple', 'order': 0}
  static const _FlutterCandiesTestPageDModuleA flutterCandiesTestPageDModuleA =
      _FlutterCandiesTestPageDModuleA();

  /// 'Show how to push new page with arguments(class)'
  ///
  /// [name] : 'flutterCandies://testPageE'
  ///
  /// [routeName] : 'testPageE'
  ///
  /// [description] : 'Show how to push new page with arguments(class)'
  ///
  /// [constructors] :
  ///
  /// TestPageE({Key? key, TestMode? testMode = const TestMode(id: 2, isTest: false), TestMode1? testMode1, Widget? child})
  ///
  /// TestPageE.test()
  ///
  /// TestPageE.requiredC({required TestMode? testMode})
  ///
  /// [exts] : {'group': 'Complex', 'order': 1}
  static const _FlutterCandiesTestPageE flutterCandiesTestPageE =
      _FlutterCandiesTestPageE();

  /// 'This is test page F. in module a'
  ///
  /// [name] : 'flutterCandies://testPageF_moduleA'
  ///
  /// [routeName] : 'testPageA'
  ///
  /// [description] : 'This is test page F. in module a'
  ///
  /// [constructors] :
  ///
  /// TestPageF({Key? key})
  ///
  /// [exts] : {'group': 'Simple', 'order': 0}
  static const _FlutterCandiesTestPageFModuleA flutterCandiesTestPageFModuleA =
      _FlutterCandiesTestPageFModuleA();

  /// 'DemoGroupPage'
  ///
  /// [name] : 'fluttercandies://demogrouppage'
  ///
  /// [routeName] : 'DemoGroupPage'
  ///
  /// [constructors] :
  ///
  /// DemoGroupPage({Key? key, required MapEntry<String, List<DemoRouteResult>> keyValue})
  static const _FluttercandiesDemogrouppage fluttercandiesDemogrouppage =
      _FluttercandiesDemogrouppage();

  /// 'MainPage'
  ///
  /// [name] : 'fluttercandies://mainpage'
  ///
  /// [routeName] : 'MainPage'
  ///
  /// [constructors] :
  ///
  /// MainPage({Key? key})
  static const _FluttercandiesMainpage fluttercandiesMainpage =
      _FluttercandiesMainpage();
}

class _FlutterCandiesTestPageF {
  const _FlutterCandiesTestPageF();

  String get name => 'flutterCandies://TestPageF';

  Map<String, dynamic> d({
    autoimport61a64860a48a0a727515bc4ec00b2fff.Key? key,
    autoimportde7367a4dccc7f836046967508c09a6c.BoxWidthStyle boxWidthStyle =
        autoimportde7367a4dccc7f836046967508c09a6c.BoxWidthStyle.max,
    autoimporte9848a6dfb6bcdd3203dea5d89c0972f.ExtendedImageMode extendedImageMode =
        autoimporte9848a6dfb6bcdd3203dea5d89c0972f.ExtendedImageMode.gesture,
    required autoimport1e2f7b96e6c9c283a2a35bf82237bf16.DragDownDetails details,
    required autoimportde7367a4dccc7f836046967508c09a6c.BlendMode blendMode,
    required autoimportd66e09f4babbdbbe015b32cc3816761d.File file,
    required List<autoimportfd790b2c4cbc8e7d99977cab283b94ab.TestMode3> modes,
    required autoimport2ac85d6b777135304f548b8ca2707514.Widget Function(String)
        function,
    required autoimportfd790b2c4cbc8e7d99977cab283b94ab.TestMode3 Function(
            autoimport1e2f7b96e6c9c283a2a35bf82237bf16.DragDownDetails)
        function1,
    required autoimport14790b17a5a1427ada8188fbf75b352c.TestMode3 Function(
            Map<autoimportfd790b2c4cbc8e7d99977cab283b94ab.TestMode1,
                autoimportfd790b2c4cbc8e7d99977cab283b94ab.TestMode2>)
        function2,
    required bool Function(String) Function(
            int,
            autoimportfd790b2c4cbc8e7d99977cab283b94ab.TestMode2 Function(
                autoimport1e2f7b96e6c9c283a2a35bf82237bf16.DragDownDetails))
        function3,
    required autoimport012d709d6940bda4da65ad673a93e8a3.AFunction aFunction,
    required autoimport012d709d6940bda4da65ad673a93e8a3.MyInt myInt,
    required autoimport012d709d6940bda4da65ad673a93e8a3.AFunction Function(
                int Function(String))
            Function(int, autoimport012d709d6940bda4da65ad673a93e8a3.MyInt Function(int))
        function4,
    autoimport012d709d6940bda4da65ad673a93e8a3.TypedefClass1 typedefClass1 =
        const autoimport012d709d6940bda4da65ad673a93e8a3.TypedefClass1(1),
  }) =>
      <String, dynamic>{
        'key': key,
        'boxWidthStyle': boxWidthStyle,
        'extendedImageMode': extendedImageMode,
        'details': details,
        'blendMode': blendMode,
        'file': file,
        'modes': modes,
        'function': function,
        'function1': function1,
        'function2': function2,
        'function3': function3,
        'aFunction': aFunction,
        'myInt': myInt,
        'function4': function4,
        'typedefClass1': typedefClass1,
        'constructorName': '',
        'argumentNames': <String>[
          'key',
          'boxWidthStyle',
          'extendedImageMode',
          'details',
          'blendMode',
          'file',
          'modes',
          'function',
          'function1',
          'function2',
          'function3',
          'aFunction',
          'myInt',
          'function4',
          'typedefClass1'
        ],
      };

  @override
  String toString() => name;
}

class _FlutterCandiesTestPageSuperParameters {
  const _FlutterCandiesTestPageSuperParameters();

  String get name => 'flutterCandies://TestPageSuperParameters';

  Map<String, dynamic> d({
    autoimport61a64860a48a0a727515bc4ec00b2fff.Key? key,
    autoimportac41f6e44f4086b72b4f7dbc1ab40cc1.TestMode? argument,
    String title = 'abc',
  }) =>
      <String, dynamic>{
        'key': key,
        'argument': argument,
        'title': title,
        'constructorName': '',
        'argumentNames': <String>['key', 'argument', 'title'],
      };

  @override
  String toString() => name;
}

class _FlutterCandiesFunc {
  const _FlutterCandiesFunc();

  String get name => 'flutterCandies://func';

  Map<String, dynamic> d(
    int a,
    String? b, {
    autoimport61a64860a48a0a727515bc4ec00b2fff.Key? key,
    bool? c,
    required double d,
  }) =>
      <String, dynamic>{
        'a': a,
        'b': b,
        'key': key,
        'c': c,
        'd': d,
        'constructorName': '',
        'argumentNames': <String>['a', 'b', 'key', 'c', 'd'],
      };

  @override
  String toString() => name;
}

class _FlutterCandiesFunc1 {
  const _FlutterCandiesFunc1();

  String get name => 'flutterCandies://func1';

  Map<String, dynamic> d(
    int a,
    String? b, {
    autoimport61a64860a48a0a727515bc4ec00b2fff.Key? key,
    bool? c,
    required double d,
  }) =>
      <String, dynamic>{
        'a': a,
        'b': b,
        'key': key,
        'c': c,
        'd': d,
        'constructorName': '',
        'argumentNames': <String>['a', 'b', 'key', 'c', 'd'],
      };

  @override
  String toString() => name;
}

class _FlutterCandiesFunc2 {
  const _FlutterCandiesFunc2();

  String get name => 'flutterCandies://func2';

  Map<String, dynamic> d(
    int a,
    String? b, {
    autoimport61a64860a48a0a727515bc4ec00b2fff.Key? key,
    bool? c,
    required double d,
  }) =>
      <String, dynamic>{
        'a': a,
        'b': b,
        'key': key,
        'c': c,
        'd': d,
        'constructorName': '',
        'argumentNames': <String>['a', 'b', 'key', 'c', 'd'],
      };

  @override
  String toString() => name;
}

class _FlutterCandiesFunc3 {
  const _FlutterCandiesFunc3();

  String get name => 'flutterCandies://func3';

  Map<String, dynamic> d(
    int a,
    String? b, {
    autoimport61a64860a48a0a727515bc4ec00b2fff.Key? key,
    bool? c,
    required double d,
  }) =>
      <String, dynamic>{
        'a': a,
        'b': b,
        'key': key,
        'c': c,
        'd': d,
        'constructorName': '',
        'argumentNames': <String>['a', 'b', 'key', 'c', 'd'],
      };

  @override
  String toString() => name;
}

class _FlutterCandiesFunc4 {
  const _FlutterCandiesFunc4();

  String get name => 'flutterCandies://func4';

  Map<String, dynamic> d(
    int a,
    String? b, {
    autoimport61a64860a48a0a727515bc4ec00b2fff.Key? key,
    bool? c,
    required double d,
  }) =>
      <String, dynamic>{
        'a': a,
        'b': b,
        'key': key,
        'c': c,
        'd': d,
        'constructorName': '',
        'argumentNames': <String>['a', 'b', 'key', 'c', 'd'],
      };

  @override
  String toString() => name;
}

class _FlutterCandiesFunc5 {
  const _FlutterCandiesFunc5();

  String get name => 'flutterCandies://func5';

  Map<String, dynamic> d(
    int a,
    String? b, {
    autoimport61a64860a48a0a727515bc4ec00b2fff.Key? key,
    bool? c,
    required double d,
  }) =>
      <String, dynamic>{
        'a': a,
        'b': b,
        'key': key,
        'c': c,
        'd': d,
        'constructorName': '',
        'argumentNames': <String>['a', 'b', 'key', 'c', 'd'],
      };

  @override
  String toString() => name;
}

class _FlutterCandiesFunc7 {
  const _FlutterCandiesFunc7();

  String get name => 'flutterCandies://func7';

  Map<String, dynamic> d(
    int a,
    String? b, {
    autoimport61a64860a48a0a727515bc4ec00b2fff.Key? key,
    bool? c,
    required double d,
  }) =>
      <String, dynamic>{
        'a': a,
        'b': b,
        'key': key,
        'c': c,
        'd': d,
        'constructorName': '',
        'argumentNames': <String>['a', 'b', 'key', 'c', 'd'],
      };

  @override
  String toString() => name;
}

class _FlutterCandiesTestPageB {
  const _FlutterCandiesTestPageB();

  String get name => '''flutterCandies://testPage' "B''';

  Map<String, dynamic> d(
          {autoimport61a64860a48a0a727515bc4ec00b2fff.Key? key,
          String? argument}) =>
      <String, dynamic>{
        'key': key,
        'argument': argument,
        'constructorName': '',
        'argumentNames': <String>['key', 'argument'],
      };

  @override
  String toString() => name;
}

class _FlutterCandiesTestPageBCopy {
  const _FlutterCandiesTestPageBCopy();

  String get name => '''flutterCandies://testPage' "B_Copy''';

  Map<String, dynamic> d(
          {autoimport61a64860a48a0a727515bc4ec00b2fff.Key? key,
          String? argument}) =>
      <String, dynamic>{
        'key': key,
        'argument': argument,
        'constructorName': '',
        'argumentNames': <String>['key', 'argument'],
      };

  @override
  String toString() => name;
}

class _FlutterCandiesTestPageBCopyCopy {
  const _FlutterCandiesTestPageBCopyCopy();

  String get name => '''flutterCandies://testPage' "B_Copy_Copy''';

  Map<String, dynamic> d(
          {autoimport61a64860a48a0a727515bc4ec00b2fff.Key? key,
          String? argument}) =>
      <String, dynamic>{
        'key': key,
        'argument': argument,
        'constructorName': '',
        'argumentNames': <String>['key', 'argument'],
      };

  @override
  String toString() => name;
}

class _FlutterCandiesTestPageBModuleA {
  const _FlutterCandiesTestPageBModuleA();

  String get name => '''flutterCandies://testPage' "B_module_a''';

  Map<String, dynamic> d({
    autoimport61a64860a48a0a727515bc4ec00b2fff.Key? key,
    autoimportac41f6e44f4086b72b4f7dbc1ab40cc1.TestMode? argument,
    String title = 'dddd',
  }) =>
      <String, dynamic>{
        'key': key,
        'argument': argument,
        'title': title,
        'constructorName': '',
        'argumentNames': <String>['key', 'argument', 'title'],
      };

  @override
  String toString() => name;
}

class _FlutterCandiesTestPageD {
  const _FlutterCandiesTestPageD();

  String get name => '''flutterCandies://testPage' "D''';

  Map<String, dynamic> d(
    String? argument, {
    autoimport61a64860a48a0a727515bc4ec00b2fff.Key? key,
    bool? optional = false,
    String? id = 'flutterCandies',
    dynamic anything,
  }) =>
      <String, dynamic>{
        'argument': argument,
        'key': key,
        'optional': optional,
        'id': id,
        'anything': anything,
        'constructorName': '',
        'argumentNames': <String>[
          'argument',
          'key',
          'optional',
          'id',
          'anything'
        ],
      };

  Map<String, dynamic> another0({required String? argument}) =>
      <String, dynamic>{
        'argument': argument,
        'constructorName': 'another0',
        'argumentNames': <String>['argument'],
      };

  Map<String, dynamic> another1(String? argument, [bool? optional = false]) =>
      <String, dynamic>{
        'argument': argument,
        'optional': optional,
        'constructorName': 'another1',
        'argumentNames': <String>['argument', 'optional'],
      };

  Map<String, dynamic> another2(String? argument) => <String, dynamic>{
        'argument': argument,
        'constructorName': 'another2',
        'argumentNames': <String>['argument'],
      };

  Map<String, dynamic> another3(
    String? argument, {
    bool? optional,
    dynamic anything,
  }) =>
      <String, dynamic>{
        'argument': argument,
        'optional': optional,
        'anything': anything,
        'constructorName': 'another3',
        'argumentNames': <String>['argument', 'optional', 'anything'],
      };

  @override
  String toString() => name;
}

class _FlutterCandiesTestPageA {
  const _FlutterCandiesTestPageA();

  String get name => 'flutterCandies://testPageA';

  Map<String, dynamic> d(
          {autoimport61a64860a48a0a727515bc4ec00b2fff.Key? key}) =>
      <String, dynamic>{
        'key': key,
        'constructorName': '',
        'argumentNames': <String>['key'],
      };

  @override
  String toString() => name;
}

class _FlutterCandiesTestPageC {
  const _FlutterCandiesTestPageC();

  String get name => 'flutterCandies://testPageC';

  Map<String, dynamic> d(
          {autoimport61a64860a48a0a727515bc4ec00b2fff.Key? key}) =>
      <String, dynamic>{
        'key': key,
        'constructorName': '',
        'argumentNames': <String>['key'],
      };

  @override
  String toString() => name;
}

class _FlutterCandiesTestPageCC {
  const _FlutterCandiesTestPageCC();

  String get name => 'flutterCandies://testPageCC';

  Map<String, dynamic> d(
    int testArg, {
    autoimport61a64860a48a0a727515bc4ec00b2fff.Key? key,
    required String testRequiredArg,
    bool? testBoolean,
  }) =>
      <String, dynamic>{
        'testArg': testArg,
        'key': key,
        'testRequiredArg': testRequiredArg,
        'testBoolean': testBoolean,
        'constructorName': '',
        'argumentNames': <String>[
          'testArg',
          'key',
          'testRequiredArg',
          'testBoolean'
        ],
      };

  Map<String, dynamic> positioned(
    int testArg, [
    bool? testBoolean,
    String testRequiredArg = '',
    autoimport61a64860a48a0a727515bc4ec00b2fff.Key? key,
  ]) =>
      <String, dynamic>{
        'testArg': testArg,
        'testBoolean': testBoolean,
        'testRequiredArg': testRequiredArg,
        'key': key,
        'constructorName': 'positioned',
        'argumentNames': <String>[
          'testArg',
          'testBoolean',
          'testRequiredArg',
          'key'
        ],
      };

  @override
  String toString() => name;
}

class _FlutterCandiesTestPageCCopy {
  const _FlutterCandiesTestPageCCopy();

  String get name => 'flutterCandies://testPageC_Copy';

  Map<String, dynamic> d(
          {autoimport61a64860a48a0a727515bc4ec00b2fff.Key? key}) =>
      <String, dynamic>{
        'key': key,
        'constructorName': '',
        'argumentNames': <String>['key'],
      };

  @override
  String toString() => name;
}

class _FlutterCandiesTestPageCCopyCopy {
  const _FlutterCandiesTestPageCCopyCopy();

  String get name => 'flutterCandies://testPageC_Copy_Copy';

  Map<String, dynamic> d(
          {autoimport61a64860a48a0a727515bc4ec00b2fff.Key? key}) =>
      <String, dynamic>{
        'key': key,
        'constructorName': '',
        'argumentNames': <String>['key'],
      };

  @override
  String toString() => name;
}

class _FlutterCandiesTestPageDModuleA {
  const _FlutterCandiesTestPageDModuleA();

  String get name => 'flutterCandies://testPageD_moduleA';

  Map<String, dynamic> d(
          {autoimport61a64860a48a0a727515bc4ec00b2fff.Key? key}) =>
      <String, dynamic>{
        'key': key,
        'constructorName': '',
        'argumentNames': <String>['key'],
      };

  @override
  String toString() => name;
}

class _FlutterCandiesTestPageE {
  const _FlutterCandiesTestPageE();

  String get name => 'flutterCandies://testPageE';

  Map<String, dynamic> d({
    autoimport61a64860a48a0a727515bc4ec00b2fff.Key? key,
    autoimport7b0d8961824b1df42839aaf6ee621592.TestMode? testMode =
        const autoimport7b0d8961824b1df42839aaf6ee621592.TestMode(
            id: 2, isTest: false),
    autoimportfd790b2c4cbc8e7d99977cab283b94ab.TestMode1? testMode1,
    autoimport2ac85d6b777135304f548b8ca2707514.Widget? child,
  }) =>
      <String, dynamic>{
        'key': key,
        'testMode': testMode,
        'testMode1': testMode1,
        'child': child,
        'constructorName': '',
        'argumentNames': <String>['key', 'testMode', 'testMode1', 'child'],
      };

  Map<String, dynamic> test() => const <String, dynamic>{
        'constructorName': 'test',
        'argumentNames': <String>[],
      };

  Map<String, dynamic> requiredC(
          {required autoimport7b0d8961824b1df42839aaf6ee621592.TestMode?
              testMode}) =>
      <String, dynamic>{
        'testMode': testMode,
        'constructorName': 'requiredC',
        'argumentNames': <String>['testMode'],
      };

  @override
  String toString() => name;
}

class _FlutterCandiesTestPageFModuleA {
  const _FlutterCandiesTestPageFModuleA();

  String get name => 'flutterCandies://testPageF_moduleA';

  Map<String, dynamic> d(
          {autoimport61a64860a48a0a727515bc4ec00b2fff.Key? key}) =>
      <String, dynamic>{
        'key': key,
        'constructorName': '',
        'argumentNames': <String>['key'],
      };

  @override
  String toString() => name;
}

class _FluttercandiesDemogrouppage {
  const _FluttercandiesDemogrouppage();

  String get name => 'fluttercandies://demogrouppage';

  Map<String, dynamic> d(
          {autoimport61a64860a48a0a727515bc4ec00b2fff.Key? key,
          required MapEntry<
                  String,
                  List<
                      autoimport19a8136766d530a60dc5d464509fd9eb
                      .DemoRouteResult>>
              keyValue}) =>
      <String, dynamic>{
        'key': key,
        'keyValue': keyValue,
        'constructorName': '',
        'argumentNames': <String>['key', 'keyValue'],
      };

  @override
  String toString() => name;
}

class _FluttercandiesMainpage {
  const _FluttercandiesMainpage();

  String get name => 'fluttercandies://mainpage';

  Map<String, dynamic> d(
          {autoimport61a64860a48a0a727515bc4ec00b2fff.Key? key}) =>
      <String, dynamic>{
        'key': key,
        'constructorName': '',
        'argumentNames': <String>['key'],
      };

  @override
  String toString() => name;
}
