// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
const List<String> routeNames = <String>[
  '''flutterCandies://testPage' "B''',
  '''flutterCandies://testPage' "D''',
  'flutterCandies://testPageA',
  'flutterCandies://testPageC',
  'flutterCandies://testPageE',
  'fluttercandies://demogrouppage',
  'fluttercandies://mainpage',
];

class Routes {
  const Routes._();

  /// "This is test ' page B."
  ///
  /// [name] : '''flutterCandies://testPage' "B'''
  ///
  /// [routeName] : 'testPageB '
  ///
  /// [description] : "This is test ' page B."
  ///
  /// [constructors] :
  ///
  /// TestPageB : [String argument]
  ///
  /// [showStatusBar] : true
  ///
  /// [pageRouteType] : PageRouteType.material
  ///
  /// [exts] : {group: Simple, order: 1}
  static const String flutterCandiesTestPageB =
      '''flutterCandies://testPage' "B''';

  /// "This is test ' page D."
  ///
  /// [name] : '''flutterCandies://testPage' "D'''
  ///
  /// [routeName] : 'testPageD '
  ///
  /// [description] : "This is test ' page D."
  ///
  /// [constructors] :
  ///
  /// TestPageD : [String(required) argument, bool optional, String id]
  ///
  /// TestPageD.another0 : [String(required) argument]
  ///
  /// TestPageD.another1 : [String(required) argument, bool optional]
  ///
  /// TestPageD.another2 : [String(required) argument]
  ///
  /// TestPageD.another3 : [String(required) argument, bool optional]
  ///
  /// [showStatusBar] : true
  ///
  /// [pageRouteType] : PageRouteType.material
  ///
  /// [exts] : {group: Complex, order: 0}
  static const String flutterCandiesTestPageD =
      '''flutterCandies://testPage' "D''';

  /// 'This is test page A.'
  ///
  /// [name] : 'flutterCandies://testPageA'
  ///
  /// [routeName] : 'testPageA'
  ///
  /// [description] : 'This is test page A.'
  ///
  /// [exts] : {group: Simple, order: 0}
  static const String flutterCandiesTestPageA = 'flutterCandies://testPageA';

  /// 'This is test page c in other module.'
  ///
  /// [name] : 'flutterCandies://testPageC'
  ///
  /// [routeName] : 'testPageC'
  ///
  /// [description] : 'This is test page c in other module.'
  ///
  /// [exts] : {group: Simple, order: 2}
  static const String flutterCandiesTestPageC = 'flutterCandies://testPageC';

  /// 'This is test page E.'
  ///
  /// [name] : 'flutterCandies://testPageE'
  ///
  /// [routeName] : 'testPageE'
  ///
  /// [description] : 'This is test page E.'
  ///
  /// [constructors] :
  ///
  /// TestPageE : [TestMode testMode, TestMode1 testMode1]
  ///
  /// TestPageE.deafult : []
  ///
  /// TestPageE.required : [TestMode(required) testMode]
  ///
  /// [exts] : {group: Complex, order: 1}
  static const String flutterCandiesTestPageE = 'flutterCandies://testPageE';

  /// 'DemoGroupPage'
  ///
  /// [name] : 'fluttercandies://demogrouppage'
  ///
  /// [routeName] : 'DemoGroupPage'
  ///
  /// [constructors] :
  ///
  /// DemoGroupPage : [MapEntry<String, List<DemoRouteResult>> keyValue]
  static const String fluttercandiesDemogrouppage =
      'fluttercandies://demogrouppage';

  /// 'MainPage'
  ///
  /// [name] : 'fluttercandies://mainpage'
  ///
  /// [routeName] : 'MainPage'
  ///
  /// [constructors] :
  ///
  /// MainPage : []
  static const String fluttercandiesMainpage = 'fluttercandies://mainpage';
}
