// dart format off
// coverage:ignore-file
// ignore_for_file: type=hint,type=lint,type=warning
//
// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: false
// **************************************************************************
library module_a_route;

export 'src/test_page_b.dart';
export 'src/test_page_c.dart';
export 'src/test_page_d.dart';
export 'src/test_page_f.dart';
