// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import,unnecessary_import
const List<String> moduleARouteNames = <String>[
  '''flutterCandies://testPage' "B_module_a''',
  'flutterCandies://testPageC',
  'flutterCandies://testPageD_moduleA',
  'flutterCandies://testPageF_moduleA',
];

class ModuleARoutes {
  const ModuleARoutes._();

  /// "This is test ' page B. in module a"
  ///
  /// [name] : '''flutterCandies://testPage' "B_module_a'''
  ///
  /// [routeName] : 'testPageB '
  ///
  /// [description] : "This is test ' page B. in module a"
  ///
  /// [pageRouteType] : PageRouteType.material
  ///
  /// [exts] : {group: Simple, order: 1}
  static const _FlutterCandiesTestPageBModuleA flutterCandiesTestPageBModuleA =
      _FlutterCandiesTestPageBModuleA();

  /// 'This is test page c in other module.'
  ///
  /// [name] : 'flutterCandies://testPageC'
  ///
  /// [routeName] : 'testPageC'
  ///
  /// [description] : 'This is test page c in other module.'
  ///
  /// [exts] : {group: Simple, order: 2}
  static const String flutterCandiesTestPageC = 'flutterCandies://testPageC';

  /// 'This is test page D. in module a'
  ///
  /// [name] : 'flutterCandies://testPageD_moduleA'
  ///
  /// [routeName] : 'testPageA'
  ///
  /// [description] : 'This is test page D. in module a'
  ///
  /// [exts] : {group: Simple, order: 0}
  static const String flutterCandiesTestPageDModuleA =
      'flutterCandies://testPageD_moduleA';

  /// 'This is test page F. in module a'
  ///
  /// [name] : 'flutterCandies://testPageF_moduleA'
  ///
  /// [routeName] : 'testPageA'
  ///
  /// [description] : 'This is test page F. in module a'
  ///
  /// [exts] : {group: Simple, order: 0}
  static const String flutterCandiesTestPageFModuleA =
      'flutterCandies://testPageF_moduleA';
}

class _FlutterCandiesTestPageBModuleA {
  const _FlutterCandiesTestPageBModuleA();

  String get name => '''flutterCandies://testPage' "B_module_a''';

  Map<String, dynamic> d({
    String? argument,
  }) =>
      <String, dynamic>{
        'argument': argument,
      };

  @override
  String toString() => name;
}
