// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************

library module_image_route;

export 'src/crop_image_demo.dart';
export 'src/custom_image_demo.dart';
export 'src/image_demo.dart';
export 'src/image_list_demo.dart';
export 'src/paint_image_demo.dart';
export 'src/photo_view_demo.dart';
export 'src/zoom_image_demo.dart';
