// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************

import 'package:example1/src/model/test_model.dart';
import 'package:example1/src/model/test_model1.dart';
import 'package:ff_annotation_route_library/ff_annotation_route_library.dart';
import 'package:flutter/widgets.dart';
import 'src/pages/complex/test_page_d.dart';
import 'src/pages/complex/test_page_e.dart';
import 'src/pages/main_page.dart';
import 'src/pages/simple/test_page_a.dart';
import 'src/pages/simple/test_page_b.dart';

// ignore_for_file: prefer_const_literals_to_create_immutables
FFRouteSettings getRouteSettings({
  @required String name,
  Map<String, dynamic> arguments,
}) {
  arguments = arguments ?? const <String, dynamic>{};
  switch (name) {
    case 'flutterCandies://testPageA':
      return FFRouteSettings(
        name: name,
        widget: TestPageA(),
        routeName: 'testPageA',
        description: 'This is test page A.',
        exts: <String, dynamic>{'group': 'Simple', 'order': 0},
      );
    case 'flutterCandies://testPageB':
      return FFRouteSettings(
        name: name,
        widget: TestPageB(
          argument: asT<String>(arguments['argument']),
        ),
        showStatusBar: true,
        routeName: 'testPageB ',
        pageRouteType: PageRouteType.material,
        description: "This is test ' page B.",
        exts: <String, dynamic>{'group': 'Simple', 'order': 1},
      );
    case 'flutterCandies://testPageD':
      return FFRouteSettings(
        name: name,
        widget: <String, Widget>{
          '': TestPageD(
            asT<String>(arguments['argument']),
            optional: asT<bool>(arguments['optional'], false),
            id: asT<String>(arguments['id'], 'flutterCandies'),
          ),
          'another0': TestPageD.another0(
            argument: asT<String>(arguments['argument']),
          ),
          'another1': TestPageD.another1(
            asT<String>(arguments['argument']),
            asT<bool>(arguments['optional'], false),
          ),
          'another2': TestPageD.another2(
            asT<String>(arguments['argument']),
          ),
          'another3': TestPageD.another3(
            asT<String>(arguments['argument']),
            optional: asT<bool>(arguments['optional']),
          ),
        }[arguments[constructorName] as String ?? ''],
        showStatusBar: true,
        routeName: 'testPageD ',
        pageRouteType: PageRouteType.material,
        description: "This is test ' page D.",
        exts: <String, dynamic>{'group': 'Complex', 'order': 0},
      );
    case 'flutterCandies://testPageE':
      return FFRouteSettings(
        name: name,
        widget: <String, Widget>{
          '': TestPageE(
            testMode: asT<TestMode>(
                arguments['testMode'], const TestMode(id: 2, isTest: false)),
            testMode1: asT<TestMode1>(arguments['testMode1']),
          ),
          'test': TestPageE.test(),
          'requiredC': TestPageE.requiredC(
            testMode: asT<TestMode>(arguments['testMode']),
          ),
        }[arguments[constructorName] as String ?? ''],
        routeName: 'testPageE',
        description: 'This is test page E.',
        exts: <String, dynamic>{'group': 'Complex', 'order': 1},
      );
    case 'fluttercandies://demogrouppage':
      return FFRouteSettings(
        name: name,
        widget: DemoGroupPage(
          keyValue: asT<MapEntry<String, List<DemoRouteResult>>>(
              arguments['keyValue']),
        ),
        routeName: 'DemoGroupPage',
      );
    case 'fluttercandies://mainpage':
      return FFRouteSettings(
        name: name,
        widget: MainPage(),
        routeName: 'MainPage',
      );
    default:
      return const FFRouteSettings(name: '404', routeName: '404_page');
  }
}
