name: Pub Publish plugin

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: Check version consistency
        run: |
          dart pub get --no-example
          dart run build_runner build -d
          git --no-pager diff --exit-code lib/src/version.gen.dart
      - name: Publish
        uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          flutter: false
          skipTests: true
          dryRunOnly: false
