name: Runnable (stable)

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  analyze:
    name: Analyze on ${{ matrix.os }} with ${{ matrix.flutter-version }} Flutter
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
      - uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
      - name: Log Dart/Flutter versions
        run: |
          dart --version
          flutter --version
      - name: Prepare dependencies
        run: dart pub get
      - name: Melos bootstrap
        uses: bluefireteam/melos-action@v3
      - name: Check Dart code formatting
        if: matrix.flutter-version != 'min'
        run: dart format . -o none --set-exit-if-changed
      - name: Analyze Dart code
        run: flutter analyze .
      - name: Publish dry-run
        if: matrix.flutter-version != 'min'
        run: dart pub publish --dry-run
