name: Runnable (stable)

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

permissions: {}

jobs:
  analyze:
    name: Analyze on ${{ matrix.os }} with ${{ matrix.flutter-version }} Flutter
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          persist-credentials: false
      - uses: flutter-actions/setup-flutter@adb607ae976a9e00473569facfc69813c637a060
        with:
          channel: stable
          cache: true
      - name: Log Dart/Flutter versions
        run: |
          dart --version
          flutter --version
      - name: Prepare dependencies
        run: dart pub get
      - name: Melos bootstrap
        uses: bluefireteam/melos-action@2982f8e4fc92440a219490009d6d05195cb1a6a5
      - name: Check Dart code formatting
        run: dart format lib -o none --set-exit-if-changed
      - name: Analyze Dart code
        run: flutter analyze .
      - name: Publish dry-run
        run: dart pub publish --dry-run
