// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// **************************************************************************
// ignore_for_file: duplicate_import,implementation_imports,library_private_types_in_public_api,multiple_combinators,prefer_const_literals_to_create_immutables,unintended_html_in_doc_comment,unnecessary_import,unused_import,unused_local_variable,unused_shown_name,unnecessary_library_name,unnecessary_library_directive
import 'dart:ui';

import 'package:example_go_router/src/router/interceptors/interface.dart';
import 'package:example_go_router/src/router/interceptors/login_interceptor.dart';
import 'package:example_go_router/src/router/interceptors/permission_interceptor.dart';
import 'package:flutter/foundation.dart';

/// The routeNames auto generated by https://github.com/fluttercandies/ff_annotation_route
const List<String> routeNames = <String>[
  '/LoginPage',
  '/PageA',
  '/PageB',
  '/index/home',
  '/index/profile',
  '/index/settings',
];

/// The routes auto generated by https://github.com/fluttercandies/ff_annotation_route
class Routes {
  const Routes._();

  /// 'LoginPage'
  ///
  /// [name] : '/LoginPage'
  ///
  /// [routeName] : 'LoginPage'
  ///
  /// [description] : 'LoginPage'
  static const _LoginPage loginPage = _LoginPage();

  /// 'PageA'
  ///
  /// [name] : '/PageA'
  ///
  /// [routeName] : 'PageA'
  ///
  /// [description] : 'PageA'
  static const _PageA pageA = _PageA();

  /// 'PageB'
  ///
  /// [name] : '/PageB'
  ///
  /// [routeName] : 'PageB'
  ///
  /// [description] : 'PageB'
  static const _PageB pageB = _PageB();

  /// 'home'
  ///
  /// [name] : '/index/home'
  ///
  /// [routeName] : 'home'
  static const _IndexHome indexHome = _IndexHome();

  /// 'profile'
  ///
  /// [name] : '/index/profile'
  ///
  /// [routeName] : 'profile'
  static const _IndexProfile indexProfile = _IndexProfile();

  /// 'settings'
  ///
  /// [name] : '/index/settings'
  ///
  /// [routeName] : 'settings'
  static const _IndexSettings indexSettings = _IndexSettings();
}

class _LoginPage {
  const _LoginPage();

  String get name => '/LoginPage';

  Map<String, dynamic> d({
    Key? key,
  }) =>
      <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _PageA {
  const _PageA();

  String get name => '/PageA';

  Map<String, dynamic> d({
    Key? key,
  }) =>
      <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _PageB {
  const _PageB();

  String get name => '/PageB';

  Map<String, dynamic> d({
    Key? key,
  }) =>
      <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _IndexHome {
  const _IndexHome();

  String get name => '/index/home';

  Map<String, dynamic> d({
    Key? key,
  }) =>
      <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _IndexProfile {
  const _IndexProfile();

  String get name => '/index/profile';

  Map<String, dynamic> d({
    Key? key,
  }) =>
      <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _IndexSettings {
  const _IndexSettings();

  String get name => '/index/settings';

  Map<String, dynamic> d({
    Key? key,
  }) =>
      <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}
