// dart format off
// coverage:ignore-file
// ignore_for_file: type=hint,type=lint,type=warning
//
// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// **************************************************************************
import 'package:example_go_router/src/router/interceptors/interface.dart';
import 'package:example_go_router/src/router/interceptors/login_interceptor.dart';
import 'package:example_go_router/src/router/interceptors/permission_interceptor.dart';
import 'package:ff_annotation_route_library/ff_annotation_route_library.dart';
import 'package:flutter/widgets.dart';

import 'src/pages/login_page.dart';
import 'src/pages/page_a.dart';
import 'src/pages/page_b.dart';
import 'src/pages/tab_home_page.dart';
import 'src/pages/tab_profile_page.dart';
import 'src/pages/tab_settings_page.dart';

/// The routeInterceptors auto generated by https://github.com/fluttercandies/ff_annotation_route
const Map<String, List<RouteInterceptor>> routeInterceptors =
    <String, List<RouteInterceptor>>{
      '/PageA': <RouteInterceptor>[LoginInterceptor()],
      '/PageB': <RouteInterceptor>[LoginInterceptor(), PermissionInterceptor()],
    };

/// The routeInterceptorTypes auto generated by https://github.com/fluttercandies/ff_annotation_route
const Map<String, List<Type>> routeInterceptorTypes = <String, List<Type>>{
  '/PageA': <Type>[ILoginInterceptor],
  '/PageB': <Type>[ILoginInterceptor, IPermissionInterceptor],
};

/// Get route settings base on route name, auto generated by https://github.com/fluttercandies/ff_annotation_route
final List<FFGoRouterRouteSettings> goRouterRouteSettings =
    <FFGoRouterRouteSettings>[
      FFGoRouterRouteSettings(
        name: '/LoginPage',
        routeName: 'LoginPage',
        description: 'LoginPage',
        builder: (Map<String, dynamic> safeArguments) =>
            LoginPage(key: asT<Key?>(safeArguments['key'])),
      ),
      FFGoRouterRouteSettings(
        name: '/PageA',
        routeName: 'PageA',
        description: 'PageA',
        builder: (Map<String, dynamic> safeArguments) =>
            PageA(key: asT<Key?>(safeArguments['key'])),
      ),
      FFGoRouterRouteSettings(
        name: '/PageB',
        routeName: 'PageB',
        description: 'PageB',
        builder: (Map<String, dynamic> safeArguments) =>
            PageB(key: asT<Key?>(safeArguments['key'])),
      ),
      FFGoRouterRouteSettings(
        name: '/index/home',
        routeName: 'home',
        builder: (Map<String, dynamic> safeArguments) =>
            TabHomePage(key: asT<Key?>(safeArguments['key'])),
      ),
      FFGoRouterRouteSettings(
        name: '/index/profile',
        routeName: 'profile',
        builder: (Map<String, dynamic> safeArguments) =>
            TabProfilePage(key: asT<Key?>(safeArguments['key'])),
      ),
      FFGoRouterRouteSettings(
        name: '/index/settings',
        routeName: 'settings',
        builder: (Map<String, dynamic> safeArguments) =>
            TabSettingsPage(key: asT<Key?>(safeArguments['key'])),
      ),
    ];
